<a href="https://colab.research.google.com/github/shah-zeb-naveed/data-science-notes/blob/main/ml_algos_from_scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# prompt: Implement cosine similarity between two vectors.

import numpy as np

def cosine_similarity(vec1, vec2):
  """Calculates the cosine similarity between two vectors.

  Args:
    vec1: The first vector.
    vec2: The second vector.

  Returns:
    The cosine similarity between the two vectors.
  """
  dot_product = np.dot(vec1, vec2)
  magnitude_vec1 = np.linalg.norm(vec1)
  magnitude_vec2 = np.linalg.norm(vec2)
  if magnitude_vec1 == 0 or magnitude_vec2 == 0:
    return 0  # Handle cases where either vector has zero magnitude.
  return dot_product / (magnitude_vec1 * magnitude_vec2)

vec1 = [1, 5]
vec2 = [3, 6]
cosine_similarity(vec1, vec2)

np.float64(0.9647638212377322)

In [ ]:
def euclidean(vec1, vec2):
  """Calculates the Euclidean distance between two vectors.

  Args:
    vec1: The first vector.
    vec2: The second vector.

  Returns:
    The Euclidean distance between the two vectors.
  """
  # replace for loop with vectorization
  return np.sqrt(np.sum((vec1 - vec2) ** 2))

vec1 = np.array([1, 5])
vec2 = np.array([3, 6])
euclidean(vec1, vec2)

np.float64(2.23606797749979)

In [ ]:
# prompt: create function that calculates softmax

import numpy as np

def softmax(x):
    """Calculates the softmax of a vector.

    Args:
      x: A NumPy array or list representing the input vector.

    Returns:
      A NumPy array representing the softmax of the input vector.
    """
    e_x = np.exp(x) # - np.max(x))  # Subtract max for numerical stability
    return e_x / np.sum(np.exp(x))

x = np.array([1, 2, 3])
softmax(x)

array([0.09003057, 0.24472847, 0.66524096])

In [ ]:
#Gini impurity and entropy calculators.

def gini_at_node(proportions):
  """Calculates the Gini impurity at a node given class proportions.

  Args:
    proportions: A list of proportions of each class at the node.
                 The proportions should sum to 1.

  Returns:
    The Gini impurity at the node.
  """
  gini = 1 - np.sum(np.square(proportions))
  return gini

def entropy_at_node(proportions):
  """Calculates the entropy at a node given class proportions.

  Args:
    proportions: A list of proportions of each class at the node.

  """

  entropy = -np.sum(proportions * np.log2(proportions))
  return entropy

proportions = [0.5, 0.5]
gini_at_node(proportions), entropy_at_node(proportions)


(np.float64(0.5), np.float64(1.0))

In [ ]:
import numpy as np

def split_gini_gain(left_child, right_child):
    n_left, n_right = len(left_child), len(right_child)
    n_total = n_left + n_right

    def gini(node):
        if len(node) == 0:
            return 0.0
        labels, counts = np.unique(node, return_counts=True)
        probs = counts / counts.sum()
        return 1.0 - np.sum(probs**2)

    gini_left = gini(left_child)
    gini_right = gini(right_child)

    return (n_left / n_total) * gini_left + (n_right / n_total) * gini_right

left_child = np.array([0, 0, 0, 0, 0, 1, 1])
right_child = np.array([1, 1, 1, 1, 1, 0, 0])

gini_impurity_value = split_gini_gain(left_child, right_child)
gini_impurity_value

np.float64(0.40816326530612246)

In [ ]:
# prompt: generate code for # KNN (including distance computation)

import numpy as np

def euclidean_distance(x1, x2):
    return np.sqrt(np.sum((x1-x2)**2))

class KNN:
    def __init__(self, k=3):
        self.k = k

    def fit(self, X, y):
        # lazy learner. nothing computed here.
        self.X_train = X
        self.y_train = y

    def predict(self, X):
        predictions = [self._predict(x) for x in X]
        return np.array(predictions)

    def _predict(self, x):
        # compute distances
        distances = [euclidean_distance(x, x_train) for x_train in self.X_train]

        # get k nearest samples, labels
        k_indices = np.argsort(distances)[:self.k]
        k_nearest_labels = [self.y_train[i] for i in k_indices]

        # majority vote, most common class label
        most_common = np.argmax(np.bincount(k_nearest_labels))

        # if regression, return np.mean(k_nearest_labels)
        return most_common

example_X = np.array([[6, 11], [25, 24], [3, 4], [4, 5]])
example_y = np.array([0, 0, 1, 1])

knn = KNN(k=3)
knn.fit(example_X, example_y)
knn.predict(np.array([[2, 2]]))

array([1])

In [ ]:
import numpy as np

class LogisticRegression:
    def __init__(self, learning_rate=0.01, epochs=1000):
        self.learning_rate = learning_rate
        self.epochs = epochs
        self.weights = None
        self.bias = None

    def sigmoid(self, z):
        return 1 / (1 + np.exp(-z))

    def forward(self, X):
        # Linear transformation
        z = np.dot(X, self.weights) + self.bias
        # Sigmoid activation (probabilities)
        predictions = self.sigmoid(z)
        return predictions

    def fit(self, X, y):
        num_samples, num_features = X.shape
        self.weights = np.zeros(num_features)
        self.bias = 0

        for epoch in range(self.epochs):
            # Forward pass
            predictions = self.forward(X)

            # Compute gradients via chain rule
            # log loss simplifies to
            dw = (1 / num_samples) * np.dot(X.T, (predictions - y))
            db = (1 / num_samples) * np.sum(predictions - y)

            # Update weights
            self.weights += self.learning_rate * (-dw)
            self.bias += self.learning_rate * (-db)

# Example input
X_train = np.array([[1, 2], [2, 3], [3, 4]])  # 3 samples, 2 features
y_train = np.array([0, 1, 0])  # Target labels

# Create and fit the model
model = LogisticRegression(learning_rate=0.01, epochs=1000)
model.fit(X_train, y_train)

# Get predictions for new data
predictions = model.forward(np.array([[1, 1]]))  # Forward pass with new sample
print("Predictions:", predictions)


Predictions: [0.42013584]


In [ ]:
# prompt: create a function for cross-entropy loss

import numpy as np

def cross_entropy_loss(y_true, y_pred):
    """Calculates the cross-entropy loss between true and predicted labels.

    Args:
        y_true: A NumPy array of true labels (one-hot encoded).
        y_pred: A NumPy array of predicted probabilities.

    Returns:
        The cross-entropy loss.
    """
    epsilon = 1e-15  # Small value to avoid log(0) errors
    y_pred = np.clip(y_pred, epsilon, 1 - epsilon) #numerical stability. for 0 and 1
    loss = -np.sum(y_true * np.log(y_pred)) / len(y_true)
    return loss


In [ ]:
# prompt: create func for MSE loss

import numpy as np

def mse_loss(y_true, y_pred):
    """Calculates the mean squared error (MSE) loss.

    Args:
        y_true: A NumPy array of true labels.
        y_pred: A NumPy array of predicted labels.

    Returns:
        The MSE loss.
    """
    return np.mean((y_true - y_pred)**2)


In [ ]:
# prompt: Decision tree node splitting (Gini impurity or entropy).

In [ ]:
# prompt: A function to find best split in DT

import numpy as np
def best_split(X, y):
    """Finds the best split for a decision tree node.

    Args:
        X: The feature matrix.
        y: The target vector.

    Returns:
        A tuple containing the best split feature index, the best split threshold,
        and the minimum Gini impurity.
    """
    best_feature_index = None
    best_threshold = None
    min_gini_impurity = 1.0  # Initialize with the maximum possible value

    num_features = X.shape[1]
    for feature_index in range(num_features):
        thresholds = np.unique(X[:, feature_index])
        for threshold in thresholds:
            left_child_indices = X[:, feature_index] <= threshold
            right_child_indices = X[:, feature_index] > threshold
            left_child_labels = y[left_child_indices]
            right_child_labels = y[right_child_indices]
            gini_impurity_gain = split_gini_gain(left_child_labels, right_child_labels)

            if gini_impurity_gain < min_gini_impurity:
                min_gini_impurity = gini_impurity_gain
                best_feature_index = feature_index
                best_threshold = threshold

    return best_feature_index, best_threshold, min_gini_impurity

# example

# data for current split
X = np.array([[1, 2], [2, 3], [3, 4], [4, 5]])
y = np.array([0, 0, 1, 1])

best_feature_index, best_threshold, min_gini_impurity = best_split(X, y)
print(best_feature_index, best_threshold, min_gini_impurity)

0 2 0.0


In [ ]:
# prompt: Linear Regression class with batch and mini-bastch gradient descent, with regularization option

import numpy as np

class LinearRegression:
    def __init__(self, learning_rate=0.01, n_iters=1000, regularization=None, lambda_param=0.1):
        self.learning_rate = learning_rate
        self.n_iters = n_iters
        self.weights = None
        self.bias = None
        self.regularization = regularization
        self.lambda_param = lambda_param

    def _run_batch_gradient_descent(self, X, y):
      n_samples = X.shape[0]
      y_predicted = np.dot(X, self.weights) + self.bias

      # chain rule
      dw = (1 / n_samples) * np.dot(X.T, (y_predicted - y))
      db = (1 / n_samples) * np.sum(y_predicted - y)

      # Regularization
      if self.regularization == 'l1':
        dw += (self.lambda_param / n_samples) * np.sign(self.weights)
      elif self.regularization == 'l2':
        dw += (2 * self.lambda_param / n_samples) * self.weights

      self.weights -= self.learning_rate * dw
      self.bias -= self.learning_rate * db

    def fit(self, X, y, batch_size=None):
        n_samples, n_features = X.shape

        # init parameters
        self.weights = np.zeros(n_features)
        self.bias = 0

        # train model
        for _ in range(self.n_iters):
          if batch_size is None: # Batch gradient descent
            for _ in range(self.n_iters):
                self._run_batch_gradient_descent(X, y)
          else: # Mini-batch gradient descent
            for i in range(0, n_samples, batch_size):
                X_batch = X[i:i+batch_size]
                y_batch = y[i:i+batch_size]
                self._run_batch_gradient_descent(X_batch, y_batch)


    def predict(self, X):
        y_approximated = np.dot(X, self.weights) + self.bias
        return y_approximated

# example

X = np.array([[1, 2], [2, 3], [3, 4], [4, 5]])
y = np.array([1, 2, 3, 4])
reg = LinearRegression(learning_rate=0.01, n_iters=1000, regularization='l1', lambda_param=0.1)
reg.fit(X, y, batch_size=2)
print(reg.predict(X))




[1.06721502 2.02743833 2.98766165 3.94788496]


In [ ]:
# prompt: implement a simple KFold class

import numpy as np

class KFoldMy:
    def __init__(self, n_splits=5):
        self.n_splits = n_splits

    def split(self, X, y=None):
        n_samples = len(X)
        fold_size = n_samples // self.n_splits
        indices = np.arange(n_samples)

        print('fold_size', fold_size)
        print('n_samples', n_samples)


        for i in range(self.n_splits):
            start = i * fold_size
            end = (i + 1) * fold_size
            #end = start + fold_size
            test_indices = indices[start:end]
            train_indices = np.concatenate([indices[:start], indices[end:]])
            print(len(train_indices), len(test_indices))
            print(train_indices, test_indices)
            yield train_indices, test_indices

In [ ]:
# prompt: K-fold cross validation

import numpy as np
from sklearn.model_selection import KFold

def k_fold_cross_validation(model, X, y, k=5):
    kf = KFoldMy(n_splits=k) # , shuffle=True, random_state=42
    scores = []
    for train_index, test_index in kf.split(X):
        X_train, X_test = X[train_index], X[test_index]
        y_train, y_test = y[train_index], y[test_index]

        model.fit(X_train, y_train)
        predictions = model.predict(X_test)
        score = mse_loss(y_test, predictions)
        scores.append(score)

    return np.mean(scores), np.std(scores)


# Example usage:
X = np.array([[1, 2], [2, 3], [3, 4], [4, 5], [5,6],[6,7], [2, 3], [3, 4], [4, 5], [5,6],[6,7]])
y = np.array([1, 2, 3, 4, 5, 6, 2, 3, 4, 5, 6])

print('input:', len(X))
reg = LinearRegression()
mean_score, std_score = k_fold_cross_validation(reg, X, y, k=3)
print(f"Mean loss: {mean_score:.4f}, Standard deviation: {std_score:.4f}")


input: 11
fold_size 3
n_samples 11
8 3
[ 3  4  5  6  7  8  9 10] [0 1 2]
8 3
[ 0  1  2  6  7  8  9 10] [3 4 5]
8 3
[ 0  1  2  3  4  5  9 10] [6 7 8]
Mean loss: 0.0000, Standard deviation: 0.0000


In [ ]:
# prompt: generate func for stratified sampling

import pandas as pd
import numpy as np

def stratified_sampling(df, column, num_samples):
    """
    Performs stratified sampling on a Pandas DataFrame.

    Args:
      df: The input DataFrame.
      column: The column to stratify by.
      num_samples: The total number of samples to draw.

    Returns:
      A new DataFrame with the stratified sample.
    """

    # Calculate proportions for each stratum
    proportions = df[column].value_counts(normalize=True)

    # Calculate the number of samples for each stratum
    samples_per_stratum = (proportions * num_samples).astype(int)
    return samples_per_stratum

    # Adjust sample sizes to match total num_samples (due to rounding)
    diff = num_samples - samples_per_stratum.sum()
    if diff > 0 :
        samples_per_stratum[samples_per_stratum.index[0]] += diff

    # Sample from each stratum
    stratified_sample = []
    for stratum, num_samples_stratum in samples_per_stratum.items():
      stratified_sample.append(df[df[column] == stratum].sample(n=num_samples_stratum, random_state=42))

    # Concatenate the samples
    return pd.concat(stratified_sample)
